// ============================================================
// v2 ADDITIONS to NeuroGuard firmware
// On-device TensorFlow Lite inference for neurological classification
// Uses the CNN+BiLSTM+Attention model exported by
//   neuroguard_model_training.py  ->  tflite_to_c_header.py
//
// Input tensor shape:  float32[1, 20, 18]
//   20 samples (1 s @ 20 Hz), 18 features per timestep
// Output tensor shape: float32[1, 8]  softmax
//
// Feature ordering MUST stay byte-identical to the Python
// training script's USED_FEATURES list, or every inference is
// garbage. Keep the two in sync at all times.
// ============================================================

// 1. Include TensorFlow Lite for Microcontrollers headers
#include <TensorFlowLite_ESP32.h>
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_error_reporter.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"

// Model weights (byte array) - regenerated by tflite_to_c_header.py
#include "neuroguard_model.h"     // provides g_model[] and g_model_len

// Scaler mean/scale for on-device normalization - ALSO regenerated by
// tflite_to_c_header.py using its --scaler flag from artifacts/*.npy.
// This eliminates hand-typed constants that silently corrupt inference
// whenever the model is retrained.
#include "neuroguard_scaler.h"    // provides g_scaler_mean[] and g_scaler_scale[]

// 2. TFLite inference toggle (BLE command "ML_ON" / "ML_OFF")
bool mlMode = true;

// 3. Model input / output layout MUST match neuroguard_model_training.py:
//      Input : float32[1, ML_SEQ_LEN=20, ML_N_FEATURES=18]
//      Output: float32[1, ML_NUM_CLASSES=8]
#define ML_SEQ_LEN         20
#define ML_N_FEATURES      18
#define ML_NUM_CLASSES     8
#define TFLITE_ARENA_SIZE  (80 * 1024)

// Sanity check: fail the build early if the auto-generated scaler
// header does not match the feature count declared above.
static_assert(sizeof(g_scaler_mean) / sizeof(g_scaler_mean[0]) == ML_N_FEATURES,
              "g_scaler_mean length mismatch - regenerate neuroguard_scaler.h");
static_assert(sizeof(g_scaler_scale) / sizeof(g_scaler_scale[0]) == ML_N_FEATURES,
              "g_scaler_scale length mismatch - regenerate neuroguard_scaler.h");

// Feature order MUST match Python USED_FEATURES list exactly:
//   0  ax           1  ay            2  az
//   3  gx           4  gy            5  gz
//   6  gyroMag      7  accelMag      8  jerk
//   9  roll         10 pitch
//   11 hr           12 spo2          13 hrv
//   14 press_delta  15 alt_delta     (BMP180 baseline-referenced)
//   16 prox         17 ambient       (APDS9960 - nocturnal + collision context)
static const int8_t ML_CLASS_TO_STATE[ML_NUM_CLASSES] = {
  ST_WALKING,      // 0 normal_walking
  ST_RESTING,      // 1 resting
  ST_ACTIVITY,     // 2 daily_activity
  ST_SLEEPWALK,    // 3 sleepwalking
  ST_SEIZURE,      // 4 epileptic_seizure
  ST_FREEZING,     // 5 freezing_of_gait
  ST_FALL,         // 6 fall
  ST_SYNCOPE       // 7 syncope
};

namespace {
  tflite::MicroErrorReporter  g_error_reporter;
  const tflite::Model        *g_ml_model    = nullptr;
  tflite::MicroInterpreter   *g_interpreter = nullptr;
  TfLiteTensor               *g_input       = nullptr;
  TfLiteTensor               *g_output      = nullptr;
  alignas(16) uint8_t         g_tensor_arena[TFLITE_ARENA_SIZE];
  bool                        g_ml_ready    = false;
}

// 4. Initialize TFLite interpreter
bool mlInit() {
  g_ml_model = tflite::GetModel(g_model);
  if (g_ml_model->version() != TFLITE_SCHEMA_VERSION) {
    Serial.printf("[ML] Schema mismatch: %d vs %d\n",
                  g_ml_model->version(), TFLITE_SCHEMA_VERSION);
    return false;
  }
  static tflite::AllOpsResolver resolver;
  static tflite::MicroInterpreter interp(
      g_ml_model, resolver, g_tensor_arena, TFLITE_ARENA_SIZE, &g_error_reporter);
  g_interpreter = &interp;
  if (g_interpreter->AllocateTensors() != kTfLiteOk) {
    Serial.println("[ML] AllocateTensors failed");
    return false;
  }
  g_input  = g_interpreter->input(0);
  g_output = g_interpreter->output(0);

  // Validate input dimensions against what the training script produced.
  if (g_input->dims->size != 3 ||
      g_input->dims->data[1] != ML_SEQ_LEN ||
      g_input->dims->data[2] != ML_N_FEATURES) {
    Serial.printf("[ML] Input shape mismatch: got [%d,%d,%d] expected [1,%d,%d]\n",
                  g_input->dims->data[0], g_input->dims->data[1],
                  g_input->dims->data[2], ML_SEQ_LEN, ML_N_FEATURES);
    return false;
  }

  g_ml_ready = true;
  Serial.printf("[ML] Model loaded (%u bytes) - input [1,%d,%d]\n",
                (unsigned)g_model_len, ML_SEQ_LEN, ML_N_FEATURES);
  return true;
}

// 5. Fill the input tensor from the sliding window buffers, then invoke.
//    Order MUST match Python USED_FEATURES list exactly.
NeuroState mlPredict(float *outConfidence) {
  if (!g_ml_ready || !bufFilled) { *outConfidence = 0.0f; return ST_IDLE; }

  // Copy the last ML_SEQ_LEN samples in chronological order.
  // bufIdx points to the NEXT write slot -> the oldest sample is at bufIdx.
  for (int k = 0; k < ML_SEQ_LEN; k++) {
    int idx = (bufIdx + k) % WINDOW_SIZE;
    float press_delta = pressBuf[idx] - baselinePressure;
    float alt_delta   = altBuf[idx]   - baselineAltitude;
    float raw[ML_N_FEATURES] = {
      axBuf[idx],       ayBuf[idx],       azBuf[idx],
      gxBuf[idx],       gyBuf[idx],       gzBuf[idx],
      gyroMagBuf[idx],  accelMagBuf[idx], jerkBuf[idx],
      rollBuf[idx],     pitchBuf[idx],
      hrBuf[idx],       spo2Buf[idx],     hrvBuf[idx],
      press_delta,      alt_delta,
      proxBuf[idx],     luxBuf[idx]
    };
    // Standard-Scaler normalization identical to training time
    for (int j = 0; j < ML_N_FEATURES; j++) {
      float z = (raw[j] - g_scaler_mean[j]) / g_scaler_scale[j];
      g_input->data.f[k * ML_N_FEATURES + j] = z;
    }
  }

  uint32_t t0 = micros();
  if (g_interpreter->Invoke() != kTfLiteOk) {
    Serial.println("[ML] Invoke failed");
    *outConfidence = 0.0f;
    return ST_IDLE;
  }
  uint32_t elapsed_us = micros() - t0;

  int   best_idx  = 0;
  float best_conf = 0.0f;
  for (int i = 0; i < ML_NUM_CLASSES; i++) {
    float v = g_output->data.f[i];
    if (v > best_conf) { best_conf = v; best_idx = i; }
  }
  *outConfidence = best_conf;

  static uint32_t ctr = 0;
  if (++ctr % 5 == 0) {
    Serial.printf("[ML] cls=%d conf=%.2f infer_us=%lu\n",
                  best_idx, best_conf, (unsigned long)elapsed_us);
  }
  return (NeuroState)ML_CLASS_TO_STATE[best_idx];
}

// 6. Smoothing: majority vote over the last 5 predictions.
//    Prevents flicker at class-transition boundaries.
#define ML_SMOOTH_WINDOW 5
static NeuroState mlRecent[ML_SMOOTH_WINDOW] = {
  ST_IDLE, ST_IDLE, ST_IDLE, ST_IDLE, ST_IDLE
};
static uint8_t mlRecentIdx = 0;

NeuroState mlSmoothedPredict(float *outConfidence) {
  NeuroState p = mlPredict(outConfidence);
  if (*outConfidence < RTC.confThresh) {
    return ST_IDLE;   // uncertain -> defer to rule-based classifier
  }
  mlRecent[mlRecentIdx++] = p;
  mlRecentIdx %= ML_SMOOTH_WINDOW;
  int counts[16] = {0};
  int best = 0, bestCount = 0;
  for (int i = 0; i < ML_SMOOTH_WINDOW; i++) {
    counts[mlRecent[i]]++;
    if (counts[mlRecent[i]] > bestCount) {
      bestCount = counts[mlRecent[i]];
      best = mlRecent[i];
    }
  }
  return (NeuroState)best;
}

// 7. BLE command handler additions (call inside CommandCallbacks::onWrite)
//      "ML_ON"   -> enable model
//      "ML_OFF"  -> disable model, fall back to rule-based classifier
//      "ML_STAT" -> report readiness and last confidence over telemetry
void mlHandleCommand(const std::string &v) {
  if (v == "ML_ON")       { mlMode = true;  Serial.println("[ML] enabled"); }
  else if (v == "ML_OFF") { mlMode = false; Serial.println("[ML] disabled"); }
  else if (v == "ML_STAT") {
    char buf[96];
    snprintf(buf, sizeof(buf),
             "{\"ml_ready\":%d,\"ml_mode\":%d,\"last_conf\":%.2f,\"n_feat\":%d}",
             g_ml_ready ? 1 : 0, mlMode ? 1 : 0, lastConfidence, ML_N_FEATURES);
    if (eventChar) {
      eventChar->setValue((uint8_t*)buf, strlen(buf));
      eventChar->notify();
    }
  }
}

// 8. In setup(), after loadCalibration() but before task creation, add:
//
//      if (!mlInit()) {
//        Serial.println("[ML] init failed - falling back to rule-based only");
//      }
//
// 9. In loop(), REPLACE the plain classify() call with the ML-preferred path:
//
//      float conf = 0;
//      NeuroState cls;
//      if (mlMode && g_ml_ready) {
//        cls = mlSmoothedPredict(&conf);
//        if (conf < RTC.confThresh) {
//          // model uncertain -> fall back to rule-based classifier
//          cls = classify(aMean, gMean, jMean,
//                         currentHR, currentSpO2, currentHRV,
//                         aMin, aMax, aMean, zcA, hrSlope,
//                         stillFrac, freeFallFrac,
//                         altDrop, currentProx, currentAmbient, &conf);
//        }
//      } else {
//        cls = classify(aMean, gMean, jMean,
//                       currentHR, currentSpO2, currentHRV,
//                       aMin, aMax, aMean, zcA, hrSlope,
//                       stillFrac, freeFallFrac,
//                       altDrop, currentProx, currentAmbient, &conf);
//      }
//      detectedClass  = cls;
//      lastConfidence = conf;
//
// 10. Add "ML_ON" / "ML_OFF" / "ML_STAT" branches inside CommandCallbacks::onWrite
//     by delegating to mlHandleCommand(v).
