// ============================================================
// NeuroGuard - TFLite Model as C Byte Array (PLACEHOLDER)
// Team SenseSphere - IEEE YESIST12 2026
//
// This file is regenerated automatically by:
//   python tflite_to_c_header.py \
//          --input  artifacts/neuroguard_int8.tflite \
//          --output neuroguard_model.h \
//          --scaler artifacts/
//
// The command above overwrites this placeholder with the real
// quantized model bytes AND regenerates neuroguard_scaler.h so
// on-device normalization matches training-time statistics.
//
// DO NOT ship this placeholder untouched - retrain and
// regenerate first, otherwise mlInit() will detect the schema
// mismatch and the firmware will fall back to the rule-based
// classifier only.
// ============================================================

#ifndef NEUROGUARD_MODEL_H
#define NEUROGUARD_MODEL_H

#ifdef __cplusplus
extern "C" {
#endif

// Placeholder: minimal TFLite header bytes so the firmware
// compiles before the AI pipeline has produced a trained model.
// Real model is thousands of bytes and will be regenerated by
// tflite_to_c_header.py after training.
alignas(8) const unsigned char g_model[] = {
    0x1c, 0x00, 0x00, 0x00, 0x54, 0x46, 0x4c, 0x33,
    0x00, 0x00, 0x0e, 0x00, 0x14, 0x00, 0x04, 0x00,
    0x00, 0x00, 0x08, 0x00, 0x0c, 0x00, 0x10, 0x00,
    0x0e, 0x00, 0x00, 0x00, 0x14, 0x00, 0x00, 0x00
};
const unsigned int g_model_len = sizeof(g_model);

#ifdef __cplusplus
}
#endif

#endif  // NEUROGUARD_MODEL_H
