"""
NeuroGuard - TFLite + Scaler -> C header exporter
Team SenseSphere - IEEE YESIST12 2026

Converts:
  1. artifacts/neuroguard_int8.tflite   ->  neuroguard_model.h
  2. artifacts/scaler_mean.npy + scaler_scale.npy  ->  neuroguard_scaler.h

The scaler header is what firmware_v2_ml_extension.cpp uses to normalize
sensor readings before inference. Regenerating both together guarantees
the on-device inputs match what the model was trained on.

Usage:
    # Model only
    python tflite_to_c_header.py \
        --input  artifacts/neuroguard_int8.tflite \
        --output neuroguard_model.h

    # Model + scaler in one shot (recommended after every retrain)
    python tflite_to_c_header.py \
        --input  artifacts/neuroguard_int8.tflite \
        --output neuroguard_model.h \
        --scaler artifacts/
"""

import argparse
import os
import numpy as np


MODEL_HEADER_TEMPLATE = """// ============================================================
// NeuroGuard - TFLite Model as C Byte Array
// Team SenseSphere - IEEE YESIST12 2026
//
// AUTO-GENERATED by tflite_to_c_header.py - DO NOT EDIT BY HAND.
// Regenerate this file after every retraining pass:
//   python tflite_to_c_header.py \\
//          --input  artifacts/neuroguard_int8.tflite \\
//          --output neuroguard_model.h \\
//          --scaler artifacts/
// ============================================================

#ifndef NEUROGUARD_MODEL_H
#define NEUROGUARD_MODEL_H

#ifdef __cplusplus
extern "C" {{
#endif

alignas(8) const unsigned char {var_name}[] = {{
{body}
}};
const unsigned int {var_name}_len = {length};

#ifdef __cplusplus
}}
#endif

#endif  // NEUROGUARD_MODEL_H
"""


SCALER_HEADER_TEMPLATE = """// ============================================================
// NeuroGuard - StandardScaler parameters (Python -> C)
// Team SenseSphere - IEEE YESIST12 2026
//
// AUTO-GENERATED by tflite_to_c_header.py from:
//   artifacts/scaler_mean.npy
//   artifacts/scaler_scale.npy
//
// Feature count: {n_features}
// Feature order MUST match USED_FEATURES in neuroguard_model_training.py:
//   {feature_comment}
// ============================================================

#ifndef NEUROGUARD_SCALER_H
#define NEUROGUARD_SCALER_H

#ifdef __cplusplus
extern "C" {{
#endif

// StandardScaler means (subtract these first)
const float g_scaler_mean[{n_features}] = {{
{mean_body}
}};

// StandardScaler scales (divide by these second)
const float g_scaler_scale[{n_features}] = {{
{scale_body}
}};

#ifdef __cplusplus
}}
#endif

#endif  // NEUROGUARD_SCALER_H
"""


DEFAULT_FEATURE_ORDER = (
    "ax, ay, az, gx, gy, gz, "
    "gyroMag, accelMag, jerk, roll, pitch, "
    "hr, spo2, hrv, "
    "press_delta, alt_delta, prox, ambient"
)


def bytes_to_c_array(data: bytes, per_line: int = 12) -> str:
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    if lines:
        lines[-1] = lines[-1].rstrip(",")
    return "\n".join(lines)


def floats_to_c_array(arr, per_line: int = 4) -> str:
    lines = []
    values = [f"{float(v):.8f}f" for v in arr]
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        lines.append("    " + ", ".join(chunk) + ",")
    if lines:
        lines[-1] = lines[-1].rstrip(",")
    return "\n".join(lines)


def export_model(tflite_path: str, out_path: str, var_name: str):
    with open(tflite_path, "rb") as f:
        data = f.read()
    body = bytes_to_c_array(data)
    header = MODEL_HEADER_TEMPLATE.format(
        var_name=var_name, body=body, length=len(data)
    )
    with open(out_path, "w") as f:
        f.write(header)
    print(f"[model]  Wrote {len(data)}-byte model into {out_path}")


def export_scaler(artifacts_dir: str, out_path: str):
    mean_npy  = os.path.join(artifacts_dir, "scaler_mean.npy")
    scale_npy = os.path.join(artifacts_dir, "scaler_scale.npy")
    if not (os.path.exists(mean_npy) and os.path.exists(scale_npy)):
        raise FileNotFoundError(
            f"Expected {mean_npy} and {scale_npy}. "
            "Run neuroguard_model_training.py first."
        )
    mean  = np.load(mean_npy).astype(np.float32)
    scale = np.load(scale_npy).astype(np.float32)
    if mean.shape != scale.shape:
        raise ValueError(f"Shape mismatch: mean {mean.shape} vs scale {scale.shape}")

    n_features = int(mean.size)
    mean_body  = floats_to_c_array(mean)
    scale_body = floats_to_c_array(scale)

    header = SCALER_HEADER_TEMPLATE.format(
        n_features=n_features,
        feature_comment=DEFAULT_FEATURE_ORDER,
        mean_body=mean_body,
        scale_body=scale_body,
    )
    with open(out_path, "w") as f:
        f.write(header)
    print(f"[scaler] Wrote {n_features}-feature scaler into {out_path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=str,
                        default="artifacts/neuroguard_int8.tflite",
                        help="Path to the .tflite model file to embed.")
    parser.add_argument("--output", type=str, default="neuroguard_model.h",
                        help="Output header for the model byte array.")
    parser.add_argument("--var-name", type=str, default="g_model",
                        help="C symbol name for the model array.")
    parser.add_argument("--scaler", type=str, default=None,
                        help="Optional artifacts/ dir. If set, also emits "
                             "neuroguard_scaler.h from scaler_mean.npy + "
                             "scaler_scale.npy.")
    parser.add_argument("--scaler-output", type=str, default="neuroguard_scaler.h",
                        help="Output header for the scaler arrays.")
    args = parser.parse_args()

    export_model(args.input, args.output, args.var_name)
    if args.scaler:
        export_scaler(args.scaler, args.scaler_output)


if __name__ == "__main__":
    main()
  
